use pcr;

delete from pcr.pcr_tables;

insert into pcr.pcr_tables (id, table_name) values (1, 'address');
insert into pcr.pcr_tables (id, table_name) values (2, 'organisation');
insert into pcr.pcr_tables (id, table_name) values (3, 'location');
insert into pcr.pcr_tables (id, table_name) values (4, 'location_contact');
insert into pcr.pcr_tables (id, table_name) values (5, 'practitioner');
insert into pcr.pcr_tables (id, table_name) values (6, 'practitioner_contact');
insert into pcr.pcr_tables (id, table_name) values (7, 'practitioner_identifier');
insert into pcr.pcr_tables (id, table_name) values (8, 'patient');
insert into pcr.pcr_tables (id, table_name) values (9, 'patient_address');
insert into pcr.pcr_tables (id, table_name) values (10, 'patient_contact');
insert into pcr.pcr_tables (id, table_name) values (11, 'patient_identifier');
insert into pcr.pcr_tables (id, table_name) values (12, 'additional_attribute');
insert into pcr.pcr_tables (id, table_name) values (13, 'additional_relationship');
insert into pcr.pcr_tables (id, table_name) values (14, 'data_entry_prompt');
insert into pcr.pcr_tables (id, table_name) values (15, 'free_text');
insert into pcr.pcr_tables (id, table_name) values (16, 'appointment_schedule');
insert into pcr.pcr_tables (id, table_name) values (17, 'appointment_schedule_practitioner');
insert into pcr.pcr_tables (id, table_name) values (18, 'appointment_slot');
insert into pcr.pcr_tables (id, table_name) values (19, 'appointment_booking');
insert into pcr.pcr_tables (id, table_name) values (20, 'appointment_attendance');
insert into pcr.pcr_tables (id, table_name) values (21, 'appointment_attendance_event');
insert into pcr.pcr_tables (id, table_name) values (22, 'gp_registration_status');
insert into pcr.pcr_tables (id, table_name) values (23, 'care_episode');
insert into pcr.pcr_tables (id, table_name) values (24, 'care_episode_additional_practitioner');
insert into pcr.pcr_tables (id, table_name) values (25, 'care_episode_status');
insert into pcr.pcr_tables (id, table_name) values (26, 'consultation');
insert into pcr.pcr_tables (id, table_name) values (27, 'accident_emergency_attendance');
insert into pcr.pcr_tables (id, table_name) values (28, 'hospital_admission');
insert into pcr.pcr_tables (id, table_name) values (29, 'hospital_ward_transfer');
insert into pcr.pcr_tables (id, table_name) values (30, 'hospital_discharge');
insert into pcr.pcr_tables (id, table_name) values (31, 'event_relationship');
insert into pcr.pcr_tables (id, table_name) values (32, 'observation');
insert into pcr.pcr_tables (id, table_name) values (33, 'flag');
insert into pcr.pcr_tables (id, table_name) values (34, 'problem');
insert into pcr.pcr_tables (id, table_name) values (35, 'procedure_request');
insert into pcr.pcr_tables (id, table_name) values (36, 'procedure');
insert into pcr.pcr_tables (id, table_name) values (37, 'device');
insert into pcr.pcr_tables (id, table_name) values (38, 'procedure_device');
insert into pcr.pcr_tables (id, table_name) values (39, 'observation_value');
insert into pcr.pcr_tables (id, table_name) values (40, 'immunisation');
insert into pcr.pcr_tables (id, table_name) values (41, 'allergy');
insert into pcr.pcr_tables (id, table_name) values (42, 'referral');
insert into pcr.pcr_tables (id, table_name) values (43, 'medication_amount');
insert into pcr.pcr_tables (id, table_name) values (44, 'medication_statement');
insert into pcr.pcr_tables (id, table_name) values (45, 'medication_order');
insert into pcr.pcr_tables (id, table_name) values (46, 'related_person');
insert into pcr.pcr_tables (id, table_name) values (47, 'related_person_contact');
insert into pcr.pcr_tables (id, table_name) values (48, 'related_person_relationship');
insert into pcr.pcr_tables (id, table_name) values (49, 'care_plan');
insert into pcr.pcr_tables (id, table_name) values (50, 'care_plan_activity');
insert into pcr.pcr_tables (id, table_name) values (51, 'care_plan_activity_target');

delete from pcr.data_entry_prompt;
insert into pcr.data_entry_prompt (id, organisation_id, prompt_text) values (-1,1,'Place holder');