-- MySQL Script generated by MySQL Workbench
-- Tue May  7 16:22:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-----------------------
-- Schema uprnentities
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uprnentities` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------


USE `uprnentities` ;

-- -----------------------------------------------------
-- Table `uprnentities`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`location` (
  `id` INT(11) NOT NULL,
  `uprn` BIGINT(20) NULL DEFAULT NULL,
  `LSOA` VARCHAR(45) NULL DEFAULT NULL,
  `MSOA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`address` (
  `id` INT(11) NOT NULL,
  `location` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `add_loc_idx` (`location` ASC),
  CONSTRAINT `add_loc`
    FOREIGN KEY (`location`)
    REFERENCES `uprnentities`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`organisation` (
  `id` INT(11) NOT NULL,
  `main_location` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ORG_LOC_idx` (`main_location` ASC),
  CONSTRAINT `ORG_LOC`
    FOREIGN KEY (`main_location`)
    REFERENCES `uprnentities`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`person` (
  `id` INT(11) NOT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`patient` (
  `id` INT(11) NOT NULL,
  `person` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `patperson_idx` (`person` ASC),
  CONSTRAINT `patperson`
    FOREIGN KEY (`person`)
    REFERENCES `uprnentities`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`episode_of_care`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`episode_of_care` (
  `id` INT(11) NOT NULL,
  `organisation` INT(11) NULL DEFAULT NULL,
  `patient` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `epiorg_idx` (`organisation` ASC),
  INDEX `epipat_idx` (`patient` ASC),
  CONSTRAINT `epiorg`
    FOREIGN KEY (`organisation`)
    REFERENCES `uprnentities`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `epipat`
    FOREIGN KEY (`patient`)
    REFERENCES `uprnentities`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`organisation_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`organisation_location` (
  `id` INT(11) NOT NULL,
  `organisation` INT(11) NULL DEFAULT NULL,
  `location` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ORLOC_idx` (`organisation` ASC),
  INDEX `LOC_idx` (`location` ASC),
  CONSTRAINT `LOC`
    FOREIGN KEY (`location`)
    REFERENCES `uprnentities`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ORLOC`
    FOREIGN KEY (`organisation`)
    REFERENCES `uprnentities`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`patient_residence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`patient_residence` (
  `id` INT(11) NOT NULL,
  `patient` INT(11) NULL DEFAULT NULL,
  `location` INT(11) NULL DEFAULT NULL,
  `from` INT(11) NULL DEFAULT NULL,
  `to` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `PAR_pat_idx` (`patient` ASC),
  INDEX `PAR_LOC_idx` (`location` ASC),
  CONSTRAINT `PAR_LOC`
    FOREIGN KEY (`location`)
    REFERENCES `uprnentities`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PAR_pat`
    FOREIGN KEY (`patient`)
    REFERENCES `uprnentities`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`person_residence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`person_residence` (
  `id` INT(11) NOT NULL,
  `person` INT(11) NULL DEFAULT NULL,
  `location` INT(11) NULL DEFAULT NULL,
  `from` DATE NULL DEFAULT NULL,
  `to` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `per_location_idx` (`location` ASC),
  INDEX `per_person_idx` (`person` ASC),
  CONSTRAINT `per_location`
    FOREIGN KEY (`location`)
    REFERENCES `uprnentities`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `per_person`
    FOREIGN KEY (`person`)
    REFERENCES `uprnentities`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`project` (
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`project_pseudonymisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`project_pseudonymisation` (
  `id` INT(11) NOT NULL,
  `project` INT(11) NULL DEFAULT NULL,
  `field` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `PS_PROJ_idx` (`project` ASC),
  CONSTRAINT `PS_PROJ`
    FOREIGN KEY (`project`)
    REFERENCES `uprnentities`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`property_matching`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`property_matching` (
  `id` INT(11) NOT NULL,
  `location` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `MATCH_LOC_idx` (`location` ASC),
  CONSTRAINT `MATCH_LOC`
    FOREIGN KEY (`location`)
    REFERENCES `uprnentities`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`pseudonym`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`pseudonym` (
  `id` INT(11) NOT NULL,
  `entity_type` INT(11) NULL DEFAULT NULL,
  `entity_id` INT(11) NULL DEFAULT NULL,
  `field` INT(11) NULL DEFAULT NULL,
  `value` VARCHAR(45) NULL DEFAULT NULL,
  `project` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `PS_project_idx` (`project` ASC),
  CONSTRAINT `PS_project`
    FOREIGN KEY (`project`)
    REFERENCES `uprnentities`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uprnentities`.`registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uprnentities`.`registration` (
  `id` INT(11) NOT NULL,
  `patient_id` INT(11) NULL DEFAULT NULL,
  `Patient` INT(11) NULL DEFAULT NULL,
  `start` DATE NULL DEFAULT NULL,
  `end` DATE NULL DEFAULT NULL,
  `type` INT(11) NULL DEFAULT NULL,
  `organisation` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `reg_patient_idx` (`patient_id` ASC),
  INDEX `reg_org_idx` (`organisation` ASC),
  CONSTRAINT `reg_org`
    FOREIGN KEY (`organisation`)
    REFERENCES `uprnentities`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reg_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `uprnentities`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
