package org.endeavourhealth.ui.json;

import java.util.Date;

public class JsonServiceSystemStatus {
    private String systemName;
    private Date lastReceivedExtract; //when last data was received into DDS
    private Date lastReceivedExtractDate; //when extract was generated by third party
    private Date lastReceivedExtractCutoff; //last data item in extract
    private boolean isProcessingUpToDate; //if last data received has been processed OK
    private boolean isProcessingInError; //if inbound processing is in error
    private Date lastProcessedExtract; //when last data was Processed into DDS
    private Date lastProcessedExtractDate; //when extract was generated by third party
    private Date lastProcessedExtractCutoff; //last data item in extract    
    private String publisherMode; //whether this interface is set to auto-fail or route to the bulk queues

    public String getSystemName() {
        return systemName;
    }

    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }

    public Date getLastReceivedExtract() {
        return lastReceivedExtract;
    }

    public void setLastReceivedExtract(Date lastReceivedExtract) {
        this.lastReceivedExtract = lastReceivedExtract;
    }

    public Date getLastReceivedExtractDate() {
        return lastReceivedExtractDate;
    }

    public void setLastReceivedExtractDate(Date lastReceivedExtractDate) {
        this.lastReceivedExtractDate = lastReceivedExtractDate;
    }

    public Date getLastReceivedExtractCutoff() {
        return lastReceivedExtractCutoff;
    }

    public void setLastReceivedExtractCutoff(Date lastReceivedExtractCutoff) {
        this.lastReceivedExtractCutoff = lastReceivedExtractCutoff;
    }

    public boolean isProcessingUpToDate() {
        return isProcessingUpToDate;
    }

    public void setProcessingUpToDate(boolean processingUpToDate) {
        isProcessingUpToDate = processingUpToDate;
    }

    public boolean isProcessingInError() {
        return isProcessingInError;
    }

    public void setProcessingInError(boolean processingInError) {
        isProcessingInError = processingInError;
    }

    public Date getLastProcessedExtract() {
        return lastProcessedExtract;
    }

    public void setLastProcessedExtract(Date lastProcessedExtract) {
        this.lastProcessedExtract = lastProcessedExtract;
    }

    public Date getLastProcessedExtractDate() {
        return lastProcessedExtractDate;
    }

    public void setLastProcessedExtractDate(Date lastProcessedExtractDate) {
        this.lastProcessedExtractDate = lastProcessedExtractDate;
    }

    public Date getLastProcessedExtractCutoff() {
        return lastProcessedExtractCutoff;
    }

    public void setLastProcessedExtractCutoff(Date lastProcessedExtractCutoff) {
        this.lastProcessedExtractCutoff = lastProcessedExtractCutoff;
    }

    public String getPublisherMode() {
        return publisherMode;
    }

    public void setPublisherMode(String publisherMode) {
        this.publisherMode = publisherMode;
    }
}
