
create or replace function helper.get_split_segments
(
	_message_id integer,
	_max_message_id integer default null
)
returns table
(
	message_id integer,
	segment_name text,
	s1 text, 
	s2 text, 
	s3 text, 
	s4 text, 
	s5 text, 
	s6 text, 
	s7 text, 
	s8 text, 
	s9 text, 
	s10 text, 
	s11 text, 
	s12 text, 
	s13 text, 
	s14 text, 
	s15 text, 
	s16 text, 
	s17 text, 
	s18 text, 
	s19 text, 
	s20 text, 
	s21 text, 
	s22 text, 
	s23 text, 
	s24 text, 
	s25 text, 
	s26 text, 
	s27 text, 
	s28 text, 
	s29 text, 
	s30 text, 
	s31 text, 
	s32 text, 
	s33 text, 
	s34 text, 
	s35 text, 
	s36 text, 
	s37 text, 
	s38 text, 
	s39 text, 
	s40 text,
	s41 text, 
	s42 text, 
	s43 text, 
	s44 text, 
	s45 text, 
	s46 text, 
	s47 text, 
	s48 text, 
	s49 text, 
	s50 text,
	s51 text, 
	s52 text
)
as $$
begin

	return query
	select 
		s.message_id,
		split_part(s.segment_text, '|', 1) as segment_name,
		split_part(s.segment_text, '|', 2) as s1,
		split_part(s.segment_text, '|', 3) as s2,
		split_part(s.segment_text, '|', 4) as s3,
		split_part(s.segment_text, '|', 5) as s4,
		split_part(s.segment_text, '|', 6) as s5,
		split_part(s.segment_text, '|', 7) as s6,
		split_part(s.segment_text, '|', 8) as s7,
		split_part(s.segment_text, '|', 9) as s8,
		split_part(s.segment_text, '|', 10) as s9,
		split_part(s.segment_text, '|', 11) as s10,
		split_part(s.segment_text, '|', 12) as s11,
		split_part(s.segment_text, '|', 13) as s12,
		split_part(s.segment_text, '|', 14) as s13,
		split_part(s.segment_text, '|', 15) as s14,
		split_part(s.segment_text, '|', 16) as s15,
		split_part(s.segment_text, '|', 17) as s16,
		split_part(s.segment_text, '|', 18) as s17,
		split_part(s.segment_text, '|', 19) as s18,
		split_part(s.segment_text, '|', 20) as s19,
		split_part(s.segment_text, '|', 21) as s20,
		split_part(s.segment_text, '|', 22) as s21,
		split_part(s.segment_text, '|', 23) as s22,
		split_part(s.segment_text, '|', 24) as s23,
		split_part(s.segment_text, '|', 25) as s24,
		split_part(s.segment_text, '|', 26) as s25,
		split_part(s.segment_text, '|', 27) as s26,
		split_part(s.segment_text, '|', 28) as s27,
		split_part(s.segment_text, '|', 29) as s28,
		split_part(s.segment_text, '|', 30) as s29,
		split_part(s.segment_text, '|', 31) as s30,
		split_part(s.segment_text, '|', 32) as s31,
		split_part(s.segment_text, '|', 33) as s32,
		split_part(s.segment_text, '|', 34) as s33,
		split_part(s.segment_text, '|', 35) as s34,
		split_part(s.segment_text, '|', 36) as s35,
		split_part(s.segment_text, '|', 37) as s36,
		split_part(s.segment_text, '|', 38) as s37,
		split_part(s.segment_text, '|', 39) as s38,
		split_part(s.segment_text, '|', 40) as s39,
		split_part(s.segment_text, '|', 41) as s40,
		split_part(s.segment_text, '|', 42) as s41,
		split_part(s.segment_text, '|', 43) as s42,
		split_part(s.segment_text, '|', 44) as s43,
		split_part(s.segment_text, '|', 45) as s44,
		split_part(s.segment_text, '|', 46) as s45,
		split_part(s.segment_text, '|', 47) as s46,
		split_part(s.segment_text, '|', 48) as s47,
		split_part(s.segment_text, '|', 49) as s48,
		split_part(s.segment_text, '|', 50) as s49,
		split_part(s.segment_text, '|', 51) as s50,
		split_part(s.segment_text, '|', 52) as s51,
		split_part(s.segment_text, '|', 53) as s52
	from helper.get_segments(_message_id, _max_message_id) s;

end;
$$ language plpgsql;